const ICON_MAP: Record<string, string> = {
  ETH: 'assets/coins/ETH.png',
  WETH: 'assets/coins/ETH.png',
  USDC: 'assets/coins/USDC.png',
  PEPE: 'assets/coins/PEPE.png',
  LINK: 'assets/coins/LINK.png',
  USDT: 'assets/coins/USDT.png',
  UNI: 'assets/coins/UNI.png',
  AAVE: 'assets/coins/AAVE.png',
  MATIC: 'assets/coins/MATIC.png',
  SHIB: 'assets/coins/SHIB.png',
  ARB: 'assets/coins/ARB.png',
  BONK: 'assets/coins/BONK.png',
  DOGE: 'assets/coins/DOGE.png',
  FLOKI: 'assets/coins/FLOKI.png',
  OP: 'assets/coins/OP.png',
  INJ: 'assets/coins/INJ.png',
  RBN: 'assets/coins/RBN.png',
  MKR: 'assets/coins/MKR.png',
  CRV: 'assets/coins/CRV.png',
  ENS: 'assets/coins/ENS.png',
  COMP: 'assets/coins/COMP.png',
  WBTC: 'assets/coins/WBTC.png',
  SOL: 'assets/coins/SOL.png',
  AVAX: 'assets/coins/AVAX.png',
  ADA: 'assets/coins/ADA.png',
  DOT: 'assets/coins/DOT.png',
  GALA: 'assets/coins/GALA.png',
  CAKE: 'assets/coins/CAKE.png',
  AXS: 'assets/coins/AXS.png',
  CHZ: 'assets/coins/CHZ.png',
  ICP: 'assets/coins/ICP.png',
  FIL: 'assets/coins/FIL.png',
  VET: 'assets/coins/VET.png',
  THETA: 'assets/coins/THETA.png',
  EOS: 'assets/coins/EOS.png',
  EGLD: 'assets/coins/EGLD.png',
  FLOW: 'assets/coins/FLOW.png',
  ALGO: 'assets/coins/ALGO.png',
  HBAR: 'assets/coins/HBAR.png',
  XTZ: 'assets/coins/XTZ.png',
  STX: 'assets/coins/STX.png',
  CRO: 'assets/coins/CRO.png',
  KAS: 'assets/coins/KAS.png',
  RUNE: 'assets/coins/RUNE.png',
  FET: 'assets/coins/FET.png',
  AGIX: 'assets/coins/AGIX.png',
  WLD: 'assets/coins/WLD.png',
  SUI: 'assets/coins/SUI.png',
  SEI: 'assets/coins/SEI.png',
  TIA: 'assets/coins/TIA.png',
  BEAM: 'assets/coins/BEAM.png',
  PENDLE: 'assets/coins/PENDLE.png',
  ONDO: 'assets/coins/ONDO.png',
  LDO: 'assets/coins/LDO.png',
  FTM: 'assets/coins/FTM.png',
  SAND: 'assets/coins/SAND.png',
  MANA: 'assets/coins/MANA.png',
  ATOM: 'assets/coins/ATOM.png',
  NEAR: 'assets/coins/NEAR.png',
  APE: 'assets/coins/APE.png',
  BONE: 'assets/coins/BONE.svg',
  WBONE: 'assets/coins/WBONE.svg',
  CHEWY: 'assets/coins/CHEWY.svg',
  LEASH: 'assets/coins/LEASH.svg',
  TREAT: 'assets/coins/TREAT.svg',
  DAI: 'assets/coins/DAI.svg',
};

const FALLBACK = 'assets/coins/ETH.png';

export function getTokenIcon(name: string): string {
  const key = (name || '').toUpperCase().trim().split('/')[0];
  return ICON_MAP[key] || FALLBACK;
}
