-- AlterTable
ALTER TABLE "DailyWinner" ADD COLUMN     "previousTimes" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];

-- AlterTable
ALTER TABLE "DailyLoser" ADD COLUMN     "previousTimes" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];

-- AlterTable
ALTER TABLE "UpdatedRRSS" ADD COLUMN     "previousTimes" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];

-- AlterTable
ALTER TABLE "HotPair" ADD COLUMN     "previousTimes" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];
